/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "index",
    {
      type: "category",
      label: "Tutorials",
      link: { type: "doc", id: "tutorials/index" },
      items: [{ type: "autogenerated", dirName: "tutorials" }]
    },
    {
      type: "category",
      label: "How-to Guides",
      link: { type: "doc", id: "how-to/index" },
      items: [{ type: "autogenerated", dirName: "how-to" }]
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "doc", id: "reference/index" },
      items: [{ type: "autogenerated", dirName: "reference" }]
    },
    {
      type: "category",
      label: "Explanation",
      link: { type: "doc", id: "explanation/index" },
      items: [{ type: "autogenerated", dirName: "explanation" }]
    },
    {
      type: "category",
      label: "Reports & Archive",
      link: { type: "doc", id: "reports/index" },
      items: [{ type: "autogenerated", dirName: "reports" }]
    }
  ]
};

module.exports = sidebars;
