import { Model, DataTypes, Sequelize } from 'sequelize';

export type CommandEnrichmentJobStatus = 'queued' | 'running' | 'completed' | 'error' | 'cancelled';

/**
 * CommandEnrichmentJob Model
 *
 * Tracks long-running enrichment of command_insights with progress + cancel.
 */
export default class CommandEnrichmentJob extends Model {
  public id!: string; // UUID string generated by app
  public status!: CommandEnrichmentJobStatus;
  public request!: Record<string, unknown>;
  public total!: number;
  public processed!: number;
  public succeeded!: number;
  public failed!: number;
  public currentCmdlet!: string | null;
  public cancelRequested!: boolean;
  public error!: string | null;
  public startedAt!: Date | null;
  public finishedAt!: Date | null;

  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  static initialize(sequelize: Sequelize) {
    CommandEnrichmentJob.init(
      {
        id: {
          type: DataTypes.STRING(36),
          primaryKey: true
        },
        status: {
          type: DataTypes.STRING(20),
          allowNull: false,
          defaultValue: 'queued'
        },
        request: {
          type: DataTypes.JSONB,
          allowNull: false,
          defaultValue: {}
        },
        total: {
          type: DataTypes.INTEGER,
          allowNull: false,
          defaultValue: 0
        },
        processed: {
          type: DataTypes.INTEGER,
          allowNull: false,
          defaultValue: 0
        },
        succeeded: {
          type: DataTypes.INTEGER,
          allowNull: false,
          defaultValue: 0
        },
        failed: {
          type: DataTypes.INTEGER,
          allowNull: false,
          defaultValue: 0
        },
        currentCmdlet: {
          type: DataTypes.STRING(200),
          allowNull: true,
          field: 'current_cmdlet'
        },
        cancelRequested: {
          type: DataTypes.BOOLEAN,
          allowNull: false,
          defaultValue: false,
          field: 'cancel_requested'
        },
        error: {
          type: DataTypes.TEXT,
          allowNull: true
        },
        startedAt: {
          type: DataTypes.DATE,
          allowNull: true,
          field: 'started_at'
        },
        finishedAt: {
          type: DataTypes.DATE,
          allowNull: true,
          field: 'finished_at'
        }
      },
      {
        sequelize,
        tableName: 'command_enrichment_jobs',
        underscored: true,
        indexes: [{ fields: ['status'] }, { fields: ['created_at'] }]
      }
    );
  }
}

