/**
 * XSS Protection Utilities
 *
 * Provides secure HTML sanitization using DOMPurify (OWASP recommended).
 * All HTML rendering MUST go through these utilities to prevent XSS attacks.
 *
 * @see https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html
 */
import DOMPurify from 'dompurify';

/**
 * Default DOMPurify configuration
 * Allows common HTML tags while blocking dangerous ones
 */
const DEFAULT_CONFIG = {
  // Allow these tags
  ALLOWED_TAGS: [
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'p', 'br', 'hr',
    'strong', 'b', 'em', 'i', 'u', 's', 'strike',
    'ul', 'ol', 'li',
    'a', 'img',
    'pre', 'code', 'blockquote',
    'table', 'thead', 'tbody', 'tr', 'th', 'td',
    'div', 'span',
    'details', 'summary',
  ],
  // Allow these attributes
  ALLOWED_ATTR: [
    'href', 'target', 'rel',
    'src', 'alt', 'title', 'width', 'height',
    'class', 'id',
    'colspan', 'rowspan',
  ],
  // Forbid dangerous protocols
  ALLOWED_URI_REGEXP: /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|sms|cid|xmpp|xxx):|[^a-z]|[a-z+.-]+(?:[^a-z+.\-:]|$))/i,
  // Always add rel="noopener noreferrer" to links
  ADD_ATTR: ['target'],
  // Force all links to have safe attributes
  FORBID_TAGS: ['script', 'style', 'iframe', 'frame', 'frameset', 'object', 'embed', 'form', 'input', 'button'],
  FORBID_ATTR: ['onerror', 'onload', 'onclick', 'onmouseover', 'onfocus', 'onblur', 'onchange', 'onsubmit'],
};

/**
 * Strict configuration for user-generated content
 * More restrictive - no links or images
 */
const STRICT_CONFIG = {
  ALLOWED_TAGS: ['p', 'br', 'strong', 'b', 'em', 'i', 'u', 'code', 'pre'],
  ALLOWED_ATTR: ['class'],
  FORBID_TAGS: ['script', 'style', 'iframe', 'frame', 'frameset', 'object', 'embed', 'form', 'input', 'button', 'a', 'img'],
  FORBID_ATTR: ['onerror', 'onload', 'onclick', 'onmouseover', 'onfocus', 'onblur', 'onchange', 'onsubmit', 'href', 'src'],
};

/**
 * Markdown-friendly configuration
 * Allows tags commonly generated by markdown parsers
 */
const MARKDOWN_CONFIG = {
  ALLOWED_TAGS: [
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'p', 'br', 'hr',
    'strong', 'b', 'em', 'i', 'u', 's', 'strike',
    'ul', 'ol', 'li',
    'a', 'img',
    'pre', 'code', 'blockquote',
    'table', 'thead', 'tbody', 'tr', 'th', 'td',
    'div', 'span',
    'details', 'summary',
    'del', 'ins', 'sup', 'sub', 'mark',
    'dl', 'dt', 'dd',
    'figure', 'figcaption',
    'abbr', 'cite', 'dfn', 'kbd', 'samp', 'var',
  ],
  ALLOWED_ATTR: [
    'href', 'target', 'rel',
    'src', 'alt', 'title', 'width', 'height',
    'class', 'id',
    'colspan', 'rowspan',
    'open', 'lang',
  ],
  FORBID_TAGS: ['script', 'style', 'iframe', 'frame', 'frameset', 'object', 'embed', 'form', 'input', 'button'],
  FORBID_ATTR: ['onerror', 'onload', 'onclick', 'onmouseover', 'onfocus', 'onblur', 'onchange', 'onsubmit'],
};

/**
 * Sanitize HTML string using DOMPurify
 *
 * @param dirty - Untrusted HTML string
 * @param config - Optional DOMPurify configuration
 * @returns Sanitized HTML string safe for rendering
 *
 * @example
 * // Basic usage
 * const safe = sanitizeHtml('<script>alert("xss")</script><p>Hello</p>');
 * // Returns: '<p>Hello</p>'
 *
 * @example
 * // With custom config
 * const safe = sanitizeHtml(html, { ALLOWED_TAGS: ['p', 'br'] });
 */
export function sanitizeHtml(dirty: string, config?: object): string {
  const mergedConfig = config ? { ...DEFAULT_CONFIG, ...config } : DEFAULT_CONFIG;
  return DOMPurify.sanitize(dirty, mergedConfig);
}

/**
 * Sanitize HTML for use with React's dangerouslySetInnerHTML
 *
 * @param dirty - Untrusted HTML string
 * @param config - Optional DOMPurify configuration
 * @returns Object safe for dangerouslySetInnerHTML
 *
 * @example
 * <div dangerouslySetInnerHTML={createSafeHtml(userContent)} />
 */
export function createSafeHtml(dirty: string, config?: object): { __html: string } {
  return { __html: sanitizeHtml(dirty, config) };
}

/**
 * Sanitize markdown-generated HTML
 * Uses markdown-friendly configuration
 *
 * @param dirty - HTML generated from markdown parser
 * @returns Sanitized HTML string
 *
 * @example
 * const html = marked.parse(markdown);
 * const safe = sanitizeMarkdownHtml(html);
 */
export function sanitizeMarkdownHtml(dirty: string): string {
  return DOMPurify.sanitize(dirty, MARKDOWN_CONFIG);
}

/**
 * Create safe HTML from markdown for React rendering
 *
 * @param dirty - HTML generated from markdown parser
 * @returns Object safe for dangerouslySetInnerHTML
 */
export function createSafeMarkdownHtml(dirty: string): { __html: string } {
  return { __html: sanitizeMarkdownHtml(dirty) };
}

/**
 * Sanitize strictly - for user comments, reviews, etc.
 * Only allows basic text formatting, no links or images
 *
 * @param dirty - Untrusted HTML string
 * @returns Strictly sanitized HTML string
 */
export function sanitizeStrict(dirty: string): string {
  return DOMPurify.sanitize(dirty, STRICT_CONFIG);
}

/**
 * Create strict safe HTML for React rendering
 *
 * @param dirty - Untrusted HTML string
 * @returns Object safe for dangerouslySetInnerHTML
 */
export function createStrictSafeHtml(dirty: string): { __html: string } {
  return { __html: sanitizeStrict(dirty) };
}

/**
 * Escape HTML entities (for plain text display)
 * Use this when you want to display HTML as text, not render it
 *
 * @param text - String that may contain HTML
 * @returns String with HTML entities escaped
 *
 * @example
 * escapeHtml('<script>') // Returns: '&lt;script&gt;'
 */
export function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Check if a string contains potential XSS vectors
 * Useful for validation before processing
 *
 * @param input - String to check
 * @returns true if potentially dangerous patterns are detected
 */
export function containsXssPatterns(input: string): boolean {
  const xssPatterns = [
    /<script\b/i,
    /javascript:/i,
    /on\w+\s*=/i,
    /<iframe\b/i,
    /<object\b/i,
    /<embed\b/i,
    /expression\s*\(/i,
    /vbscript:/i,
    /data:\s*text\/html/i,
  ];

  return xssPatterns.some(pattern => pattern.test(input));
}

/**
 * Hook DOMPurify for additional security logging
 * Call once at app initialization for XSS attempt monitoring
 */
export function initXssMonitoring(): void {
  // Log when tags are removed
  DOMPurify.addHook('uponSanitizeElement', (node, data) => {
    if (data.tagName && ['script', 'iframe', 'object', 'embed'].includes(data.tagName.toLowerCase())) {
      console.warn('[XSS Protection] Blocked dangerous element:', data.tagName);
    }
  });

  // Log when attributes are removed
  DOMPurify.addHook('uponSanitizeAttribute', (node, data) => {
    if (data.attrName && data.attrName.toLowerCase().startsWith('on')) {
      console.warn('[XSS Protection] Blocked event handler:', data.attrName);
    }
  });
}

// Export configs for advanced usage
export const sanitizeConfigs = {
  DEFAULT: DEFAULT_CONFIG,
  STRICT: STRICT_CONFIG,
  MARKDOWN: MARKDOWN_CONFIG,
};

export default {
  sanitizeHtml,
  createSafeHtml,
  sanitizeMarkdownHtml,
  createSafeMarkdownHtml,
  sanitizeStrict,
  createStrictSafeHtml,
  escapeHtml,
  containsXssPatterns,
  initXssMonitoring,
  configs: sanitizeConfigs,
};
