FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build:prod

FROM node:20-alpine

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./package.json

ENV NODE_ENV=production
ENV VITE_PORT=3090
ENV DOCKER_ENV=true

EXPOSE 3090

CMD ["npx", "vite", "preview", "--host", "0.0.0.0", "--port", "3090"]
